services:
  - type: web
    name: cloud-app
    env: node
    plan: free
    region: oregon
    repo: https://github.com/haruaki2416/Holy-Unblocker
    branch: master
    buildCommand: npm install
    startCommand: node backend.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
